on:
  workflow_dispatch:
  push:

jobs:
  generate-matrix:
    name: "Generate matrix from cabal"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: webdevred/get-tested@b1b72bae5d99ee355358b40b1d2e8aaf82ef4806
        with:
          cabal-file: ./get-tested-example.cabal
          ubuntu-version: "latest,22.04"
          macos-version: "latest"
          newest: true
          version: get-tested-head
